-- SecureMailScope — Supabase migration for Option 3
-- Creates the analysis_results table combining raw cyber team data and ML fields.

CREATE TABLE IF NOT EXISTS analysis_results (
    -- Cyber Team's Raw Columns
    id INTEGER PRIMARY KEY, -- From SQLite
    captured_at TEXT,
    src_ip TEXT,
    dst_ip TEXT,
    src_port INTEGER,
    dst_port INTEGER,
    negotiated_version TEXT,
    negotiated_cipher TEXT,
    cert_subject TEXT,
    cert_issuer TEXT,
    cert_expiry TEXT,
    cert_days_to_expiry NUMERIC,
    cert_sig_algorithm TEXT,
    flag_deprecated_version INTEGER,
    flag_weak_cipher INTEGER,
    flag_no_forward_secrecy INTEGER,
    flag_weak_cert_signature INTEGER,
    flag_cert_expiring_soon INTEGER,
    label TEXT,
    source_pcap TEXT,
    
    -- ML Pipeline Columns (Initially NULL when cyber team inserts)
    result_id text, -- UUID generated by ML
    analyzed_at timestamptz,
    session_id text,
    protocol text,
    tls_version text,
    cipher_suite text,
    risk_level text,
    risk_confidence float8,
    class_probabilities jsonb,
    is_anomaly integer, -- 0 or 1
    anomaly_score float8,
    security_score integer,
    detected_weaknesses jsonb,
    recommendations jsonb
);

-- Index for the dashboard's "most recent N" query
CREATE INDEX IF NOT EXISTS idx_analysis_results_analyzed_at
    ON analysis_results (analyzed_at DESC);

-- Index for filtering by risk level
CREATE INDEX IF NOT EXISTS idx_analysis_results_risk_level
    ON analysis_results (risk_level);

-- Index to quickly find unprocessed rows
CREATE INDEX IF NOT EXISTS idx_analysis_results_unprocessed
    ON analysis_results (id)
    WHERE risk_level IS NULL;

-- RLS disabled for direct anon access
ALTER TABLE public.analysis_results DISABLE ROW LEVEL SECURITY;
